### ISSUE TITLE
Using regular+tpad for function 1B resulted more miss than just regular

### ISSUE THREAD

**Issue by SPTKL** [ishiland/python-geosupport#14] opened 2019-01-30 15:14 UTC
Hi there, 

Thank you for developing this package, it's been super helpful for my geocoding process. 
I have 1 question tho. After I finished geocoding using function 1B (the g.address function, which only contains PAD), I tried to use the same function with mode='tpad' and mode='regular+tpad', which for some reason resulted more entries that couldn't find a lon and lat. 

Also mode 'tpad' and 'regular+tpad' contains the exact same numbers of entries that couldn't find lon and lat. I know in your README, 'regular+tpad' is not even an option, but somehow it works? 

It would be super helpful if you can explain this curious case, thanks!

**Comment by docmarionum1** [comment] 2019-01-30 19:09
Can you give some specific examples of the function calls you're making?

**Comment by SPTKL** [comment] 2019-01-31 15:30
`geo = g.address(house_number=num, street_name=street, borough_code=borough,  mode='regular+tpad')`

**Comment by docmarionum1** [comment] 2019-01-31 18:41
I tried the same thing and didn't notice anything different. What specific address are you noticing it with?

**Comment by SPTKL** [comment] 2019-01-31 19:57
'g['1A'](house_number='204-11', street_name='38 ave', borough_code='qn')['Longitude']
g['1A'](house_number='204-11', street_name='38 ave', borough_code='qn', mode='regular+tpad')['Longitude']' 

the first would return a longitude, the second won't, why is that? I thought regular is the default mode and regular_tpad is the union of regular and tpad, hence the second should return a longitude too

**Comment by docmarionum1** [comment] 2019-01-31 20:41
'regular+tpad' isn't an expected input, but as long as mode contains 'tpad' it will set tpad to True. Essentially, 'regular+tpad' == 'tpad'.

As for why the longitude doesn't come back from Geosupport, I'm not sure. If you look at the response there are return codes that indicate that there was a conflict between the PAD and TPAD files.

```
'Reason Code': '*',
'Reason Code Qualifier': '2',
'Warning Code': '',
'Geosupport Return Code (GRC)': '01',
'Message': 'TPAD BBL USED, NO EXISTING PAD BBL',

'TPAD BIN Status (for DM job)': '',
'TPAD New BIN': '4618783',
'TPAD New BIN Status': '0',
'TPAD Conflict Flag': '2',
```

It looks like the BIN and BBL associated with that address changed in TPAD. I'm not sure if it's expected behavior in this case to not return latitude and longitude. You'd have to ask the Geosupport developers. 

Here's some documentation about TPAD and error codes:

https://nycplanning.github.io/Geosupport-UPG/appendices/appendix17/
https://nycplanning.github.io/Geosupport-UPG/chapters/chapterVI/section11/

Closing as this seems to be an issue with Geosupport itself and not python-geosupport.

**Closed by docmarionum1** 2019-01-31 20:41 UTC

**Comment by SPTKL** [comment] 2019-02-01 14:44
Thanks
